Repository PlasmaFAIR/fortitude, pull requests merged in 2025-02, with the labels that each got.

#315 Fix some issues with newlines in fixes on Windows
  .github/workflows/test.yml
  fortitude/src/ast.rs
  fortitude/src/rules/bugprone/mod.rs
  fortitude/src/rules/io/mod.rs
  fortitude/src/rules/modules/mod.rs
  fortitude/src/rules/obsolescent/mod.rs
  fortitude/src/rules/precision/mod.rs
  fortitude/src/rules/readability/mod.rs
  fortitude/src/rules/style/line_length.rs
  fortitude/src/rules/style/mod.rs
  fortitude/src/rules/style/whitespace.rs
  fortitude/src/rules/typing/mod.rs
  fortitude/src/test.rs
  fortitude/tests/check.rs
Labels: bug

#312 Decouple CLI and config file
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  docs/configuration.md
  docs/rules.md
  docs/rules/multiple-statements-per-line.md
  docs/rules/superfluous-semicolon.md
  docs/settings.md
  fortitude/Cargo.toml
  fortitude/src/check.rs
  fortitude/src/configuration.rs
  fortitude/src/fs.rs
  fortitude/src/lib.rs
  fortitude/src/options.rs
  fortitude/src/options_base.rs
  fortitude/src/rule_selector.rs
  fortitude/tests/check.rs
  fortitude_dev/Cargo.toml
  fortitude_dev/src/generate_all.rs
  fortitude_dev/src/generate_docs.rs
  fortitude_dev/src/generate_options.rs
  fortitude_dev/src/main.rs
Labels: configuration

#319 Add `Settings` struct for final resolved settings
  docs/configuration.md
  fortitude/src/check.rs
  fortitude/src/cli.rs
  fortitude/src/configuration.rs
  fortitude/src/fs.rs
  fortitude/src/lib.rs
  fortitude/src/rule_selector.rs
  fortitude/src/rules/style/line_length.rs
  fortitude/src/rules/style/mod.rs
  fortitude/src/settings.rs
  fortitude/src/show_files.rs
  fortitude/src/show_settings.rs
  fortitude/src/test.rs
Labels: internal

#311 Add rule to flag trailing backslash
  docs/rules.md
  docs/rules/trailing-backslash.md
  fortitude/resources/test/fixtures/bugprone/B011.F90
  fortitude/src/rules/bugprone/mod.rs
  fortitude/src/rules/bugprone/snapshots/fortitude__rules__bugprone__tests__trailing-backslash_B011.F90.snap
  fortitude/src/rules/bugprone/trailing_backslash.rs
  fortitude/src/rules/mod.rs
Labels: rule

#325 Bump ruff packages to 0.9.6
  Cargo.lock
  Cargo.toml
  fortitude/src/check.rs
  fortitude/src/fix/mod.rs
  fortitude/src/lib.rs
  fortitude/src/locator.rs
  fortitude/src/rules/bugprone/select_default.rs
  fortitude/src/rules/bugprone/trailing_backslash.rs
  fortitude/src/rules/error/allow_comments.rs
  fortitude/src/rules/error/ioerror.rs
  fortitude/src/rules/error/syntax_error.rs
  fortitude/src/rules/filesystem/extensions.rs
  fortitude/src/rules/io/magic_io_unit.rs
  fortitude/src/rules/io/missing_specifier.rs
  fortitude/src/rules/modules/accessibility_statements.rs
  fortitude/src/rules/modules/external_functions.rs
  fortitude/src/rules/modules/file_contents.rs
  fortitude/src/rules/modules/include_statement.rs
  fortitude/src/rules/modules/use_statements.rs
  fortitude/src/rules/obsolescent/common_blocks.rs
  fortitude/src/rules/obsolescent/computed_goto.rs
  fortitude/src/rules/obsolescent/entry_statement.rs
  fortitude/src/rules/obsolescent/pause_statement.rs
  fortitude/src/rules/obsolescent/specific_names.rs
  fortitude/src/rules/obsolescent/statement_functions.rs
  fortitude/src/rules/precision/double_precision.rs
  fortitude/src/rules/precision/implicit_kinds.rs
  fortitude/src/rules/precision/kind_suffixes.rs
  fortitude/src/rules/readability/magic_numbers.rs
  fortitude/src/rules/style/double_colon_in_decl.rs
  fortitude/src/rules/style/end_statements.rs
  fortitude/src/rules/style/exit_labels.rs
  fortitude/src/rules/style/line_length.rs
  fortitude/src/rules/style/old_style_array_literal.rs
  fortitude/src/rules/style/relational_operators.rs
  fortitude/src/rules/style/semicolons.rs
  fortitude/src/rules/style/whitespace.rs
  fortitude/src/rules/testing/test_rules.rs
  fortitude/src/rules/typing/assumed_size.rs
  fortitude/src/rules/typing/derived_default_init.rs
  fortitude/src/rules/typing/external.rs
  fortitude/src/rules/typing/implicit_typing.rs
  fortitude/src/rules/typing/init_decls.rs
  fortitude/src/rules/typing/intent.rs
  fortitude/src/rules/typing/literal_kinds.rs
  fortitude/src/rules/typing/star_kinds.rs
  fortitude_macros/src/map_codes.rs
Labels: internal

#324 Mark rules as `Default` or `Optional` in `map_codes`
  docs/rules.md
  docs/rules/assumed-size-character-intent.md
  docs/rules/assumed-size.md
  docs/rules/common-block.md
  docs/rules/computed-go-to.md
  docs/rules/deprecated-assumed-size-character.md
  docs/rules/deprecated-relational-operator.md
  docs/rules/entry-statement.md
  docs/rules/external-procedure.md
  docs/rules/implicit-external-procedures.md
  docs/rules/implicit-typing.md
  docs/rules/initialisation-in-declaration.md
  docs/rules/interface-implicit-typing.md
  docs/rules/invalid-rule-code-or-name.md
  docs/rules/io-error.md
  docs/rules/line-too-long.md
  docs/rules/literal-kind-suffix.md
  docs/rules/literal-kind.md
  docs/rules/missing-accessibility-statement.md
  docs/rules/missing-default-case.md
  docs/rules/missing-default-pointer-initalisation.md
  docs/rules/missing-double-colon.md
  docs/rules/missing-exit-or-cycle-label.md
  docs/rules/missing-intent.md
  docs/rules/missing-intrinsic.md
  docs/rules/non-standard-file-extension.md
  docs/rules/old-style-array-literal.md
  docs/rules/pause-statement.md
  docs/rules/procedure-not-in-module.md
  docs/rules/specific-name.md
  docs/rules/star-kind.md
  docs/rules/statement-function.md
  docs/rules/superfluous-implicit-none.md
  docs/rules/superfluous-semicolon.md
  docs/rules/syntax-error.md
  docs/rules/trailing-backslash.md
  docs/rules/trailing-whitespace.md
  docs/rules/unnamed-end-statement.md
  docs/rules/use-all.md
  fortitude/src/rules/mod.rs
  fortitude/src/settings.rs
  fortitude_dev/src/generate_docs.rs
  fortitude_dev/src/generate_rules_table.rs
  fortitude_macros/src/map_codes.rs
Labels: configuration

#330 Add `--statistics` CLI flag to show counts of violations
  docs/configuration.md
  fortitude/src/check.rs
  fortitude/src/cli.rs
  fortitude/src/message/mod.rs
  fortitude/src/printer.rs
  fortitude/tests/check.rs
Labels: cli

#332 Fix `--show-statistics` test for updated rule codes
  fortitude/tests/check.rs
Labels: internal

#334 Add rules for unused/duplicated/redirected allow comments
  docs/configuration.md
  docs/index.md
  docs/rules.md
  docs/rules/disabled-allow-comment.md
  docs/rules/duplicated-allow-comment.md
  docs/rules/invalid-rule-code-or-name.md
  docs/rules/redirected-allow-comment.md
  docs/rules/unused-allow-comment.md
  fortitude/resources/test/fixtures/fortitude/FORT001.f90
  fortitude/resources/test/fixtures/fortitude/FORT002.f90
  fortitude/resources/test/fixtures/fortitude/FORT003.f90
  fortitude/resources/test/fixtures/fortitude/FORT004.f90
  fortitude/resources/test/fixtures/fortitude/FORT005.f90
  fortitude/src/allow_comments.rs
  fortitude/src/check.rs
  fortitude/src/cli.rs
  fortitude/src/configuration.rs
  fortitude/src/lib.rs
  fortitude/src/registry.rs
  fortitude/src/rules/error/allow_comments.rs
  fortitude/src/rules/error/mod.rs
  fortitude/src/rules/fortitude/allow_comments.rs
  fortitude/src/rules/fortitude/mod.rs
  fortitude/src/rules/fortitude/snapshots/fortitude__rules__fortitude__tests__disabled-allow-comment_FORT005.f90.snap
  fortitude/src/rules/fortitude/snapshots/fortitude__rules__fortitude__tests__duplicated-allow-comment_FORT004.f90.snap
  fortitude/src/rules/fortitude/snapshots/fortitude__rules__fortitude__tests__invalid-rule-code-or-name_FORT001.f90.snap
  fortitude/src/rules/fortitude/snapshots/fortitude__rules__fortitude__tests__redirected-allow-comment_FORT003.f90.snap
  fortitude/src/rules/fortitude/snapshots/fortitude__rules__fortitude__tests__unused-allow-comment_FORT002.f90.snap
  fortitude/src/rules/mod.rs
  fortitude/src/settings.rs
  fortitude/src/test.rs
  fortitude/tests/check.rs
Labels: rule

#337 Move rules from preview
  docs/rules.md
  docs/rules/default-public-accessibility.md
  docs/rules/implicit-external-procedures.md
  docs/rules/missing-accessibility-statement.md
  fortitude/src/rules/mod.rs
  test.f90
Labels: preview

#336 Don't raise linter violations or apply fixes when syntax errors are detected
  fortitude/src/check.rs
  fortitude/tests/check.rs
  fortitude_macros/src/map_codes.rs
Labels: bug

#340 Add command to generate shell completion scripts
  Cargo.lock
  Cargo.toml
  docs/configuration.md
  fortitude/Cargo.toml
  fortitude/src/cli.rs
  fortitude/src/main.rs
Labels: cli
