Repository PlasmaFAIR/fortitude, pull requests merged in 2025-04, with the labels that each got.

#398 Fix rule table EOF whitespace
  docs/rules.md
  fortitude_dev/src/generate_rules_table.rs
Labels: internal

#399 Set fortitude as default crate in workspace
  Cargo.toml
  README.dev.md
Labels: internal

#400 docs: Include changelog on website
  docs/release_notes.md
  mkdocs.yml
  requirements.docs.txt
Labels: documentation, internal

#403 Prepare for version 0.7.2 release
  CHANGELOG.md
  CITATION.cff
  Cargo.lock
  README.dev.md
  docs/integrations.md
  fortitude/Cargo.toml
  pyproject.toml
Labels: internal

#407 Add rule for `missing-end-label`
  docs/rules.md
  docs/rules/missing-end-label.md
  fortitude/resources/test/fixtures/correctness/C143.f90
  fortitude/src/rules/correctness/exit_labels.rs
  fortitude/src/rules/correctness/mod.rs
  fortitude/src/rules/correctness/snapshots/fortitude__rules__correctness__tests__missing-end-label_C143.f90.snap
  fortitude/src/rules/mod.rs
Labels: rule

#420 Apply auto-fixes for recent clippy update
  fortitude/src/allow_comments.rs
  fortitude/src/check.rs
  fortitude/src/rule_selector.rs
Labels: internal

#425 Add helper methods for start/end node offsets as `TextSize`
  fortitude/src/allow_comments.rs
  fortitude/src/ast.rs
  fortitude/src/lib.rs
  fortitude/src/rules/correctness/derived_default_init.rs
  fortitude/src/rules/correctness/exit_labels.rs
  fortitude/src/rules/correctness/implicit_typing.rs
  fortitude/src/rules/correctness/use_statements.rs
  fortitude/src/rules/modernisation/include_statement.rs
  fortitude/src/rules/style/double_colon_in_decl.rs
  fortitude/src/rules/style/keywords.rs
  fortitude/src/rules/style/strings.rs
  fortitude/src/rules/style/whitespace.rs
Labels: internal
