Repository PlasmaFAIR/fortitude, pull requests merged in 2025-03, with the labels that each got.

#342 Bump tree-sitter-fortran to v0.5.0
  Cargo.lock
  fortitude/Cargo.toml
Labels: internal

#335 Bump version to 0.7.0
  .github/workflows/release.yml
  BREAKING_CHANGES.md
  CHANGELOG.md
  CITATION.cff
  Cargo.lock
  README.md
  docs/index.md
  fortitude/Cargo.toml
  pyproject.toml
Labels: internal

#343 CI: Fix release workflow to allow setting tag on manual dispatch
  .github/workflows/release.yml
Labels: ci

#344 CI: Set `cargo-dist` config to match ruff's
  .github/workflows/release.yml
  dist-workspace.toml
Labels: ci

#346 Include LICENSE in sdist
  fortitude/Cargo.toml
  pyproject.toml
Labels: internal

#350 docs(index): fix link to best practices
  docs/index.md
Labels: documentation

#351 Move `default-public-accessibility` highlight to `public` statement
  fortitude/src/rules/correctness/accessibility_statements.rs
  fortitude/src/rules/correctness/snapshots/fortitude__rules__correctness__tests__default-public-accessibility_C132.f90.snap
Labels: bug

#357 docs: fix links to best practice
  README.md
  docs/rules/double-precision.md
  docs/rules/implicit-real-kind.md
  docs/rules/no-real-suffix.md
  fortitude/src/rules/correctness/implicit_kinds.rs
  fortitude/src/rules/correctness/kind_suffixes.rs
  fortitude/src/rules/modernisation/double_precision.rs
Labels: documentation

#358 Write to stdout even when no fixes are applied in stdin mode
  README.md
  docs/configuration.md
  docs/index.md
  fortitude/src/check.rs
  fortitude/tests/check.rs
Labels: bug

#361 Use `pre-commit` in place of custom `.githooks` scripts
  .githooks/pre-commit
  .pre-commit-config.yaml
  README.dev.md
Labels: internal

#360 Update introduction to `README.dev.md`
  README.dev.md
Labels: documentation

#354 Expand rule for `character*(*)` to handle `character*N`, `character*(:)`, and `character*(expression)`
  docs/rules.md
  docs/rules/deprecated-assumed-size-character.md
  docs/rules/deprecated-character-syntax.md
  docs/rules/old-style-character-syntax.md
  fortitude/resources/test/fixtures/obsolescent/OB061.f90
  fortitude/src/allow_comments.rs
  fortitude/src/configuration.rs
  fortitude/src/registry.rs
  fortitude/src/rule_redirects.rs
  fortitude/src/rule_selector.rs
  fortitude/src/rules/fortitude/allow_comments.rs
  fortitude/src/rules/fortitude/snapshots/fortitude__rules__fortitude__tests__redirected-allow-comment_FORT003.f90.snap
  fortitude/src/rules/mod.rs
  fortitude/src/rules/obsolescent/assumed_size_character_syntax.rs
  fortitude/src/rules/obsolescent/deprecated_character_syntax.rs
  fortitude/src/rules/obsolescent/mod.rs
  fortitude/src/rules/obsolescent/snapshots/fortitude__rules__obsolescent__tests__deprecated-assumed-size-character_OB061.f90.snap
  fortitude/src/rules/obsolescent/snapshots/fortitude__rules__obsolescent__tests__deprecated-character-syntax_OB061.f90.snap
  fortitude_macros/src/rule_namespace.rs
Labels: rule

#362 Switch to `ruff`'s `version` machinery
  Cargo.lock
  docs/configuration.md
  fortitude/Cargo.toml
  fortitude/build.rs
  fortitude/src/cli.rs
  fortitude/src/lib.rs
  fortitude/src/main.rs
  fortitude/src/message/sarif.rs
  fortitude/src/snapshots/fortitude__version__tests__version_formatting.snap
  fortitude/src/snapshots/fortitude__version__tests__version_formatting_with_commit_info.snap
  fortitude/src/snapshots/fortitude__version__tests__version_formatting_with_commits_since_last_tag.snap
  fortitude/src/snapshots/fortitude__version__tests__version_serializable.snap
  fortitude/src/version.rs
Labels: internal

#380 docs: Remove readthedocs version menu from nav bar
  docs/javascript/readthedocs.js
Labels: documentation, internal

#379 Bump version to 0.7.1
  CHANGELOG.md
  CITATION.cff
  Cargo.lock
  docs/integrations.md
  fortitude/Cargo.toml
  pyproject.toml
Labels: internal

#382 Fix testcase extension in generated rule template
  scripts/add_rule.py
Labels: internal

#387 Fix `fpm.toml` examples in `docs/settings.md`
  docs/settings.md
  fortitude_dev/src/generate_options.rs
Labels: documentation

#388 Fix doc tests and run all tests in CI
  .config/nextest.toml
  .github/workflows/test.yml
  docs/rules/include-statement.md
  fortitude/src/lib.rs
  fortitude/src/locator.rs
  fortitude/src/message/diff.rs
  fortitude/src/message/mod.rs
  fortitude/src/options_base.rs
  fortitude/src/rules/modernisation/include_statement.rs
  fortitude/src/rules/obsolescent/snapshots/fortitude__rules__obsolescent__tests__statement-function_OB001.f90.snap
  fortitude/src/rules/style/snapshots/fortitude__rules__style__tests__incorrect-space-before-comment_S121.f90.snap
  fortitude/src/version.rs
Labels: internal

#391 Rule docs should have newline at end of file
  docs/rules/assumed-size-character-intent.md
  docs/rules/assumed-size.md
  docs/rules/common-block.md
  docs/rules/computed-go-to.md
  docs/rules/default-public-accessibility.md
  docs/rules/deprecated-character-syntax.md
  docs/rules/deprecated-relational-operator.md
  docs/rules/disabled-allow-comment.md
  docs/rules/double-precision.md
  docs/rules/duplicated-allow-comment.md
  docs/rules/entry-statement.md
  docs/rules/exit-or-cycle-in-unlabelled-loop.md
  docs/rules/external-procedure.md
  docs/rules/implicit-external-procedures.md
  docs/rules/implicit-real-kind.md
  docs/rules/implicit-typing.md
  docs/rules/include-statement.md
  docs/rules/incorrect-space-before-comment.md
  docs/rules/initialisation-in-declaration.md
  docs/rules/interface-implicit-typing.md
  docs/rules/invalid-rule-code-or-name.md
  docs/rules/io-error.md
  docs/rules/line-too-long.md
  docs/rules/literal-kind-suffix.md
  docs/rules/literal-kind.md
  docs/rules/magic-io-unit.md
  docs/rules/magic-number-in-array-size.md
  docs/rules/missing-accessibility-statement.md
  docs/rules/missing-action-specifier.md
  docs/rules/missing-default-case.md
  docs/rules/missing-default-pointer-initalisation.md
  docs/rules/missing-double-colon.md
  docs/rules/missing-exit-or-cycle-label.md
  docs/rules/missing-intent.md
  docs/rules/missing-intrinsic.md
  docs/rules/multiple-modules.md
  docs/rules/multiple-statements-per-line.md
  docs/rules/no-real-suffix.md
  docs/rules/non-portable-io-unit.md
  docs/rules/non-standard-file-extension.md
  docs/rules/old-style-array-literal.md
  docs/rules/pause-statement.md
  docs/rules/procedure-not-in-module.md
  docs/rules/program-with-module.md
  docs/rules/redirected-allow-comment.md
  docs/rules/specific-name.md
  docs/rules/star-kind.md
  docs/rules/statement-function.md
  docs/rules/superfluous-implicit-none.md
  docs/rules/superfluous-semicolon.md
  docs/rules/syntax-error.md
  docs/rules/trailing-backslash.md
  docs/rules/trailing-whitespace.md
  docs/rules/unnamed-end-statement.md
  docs/rules/unused-allow-comment.md
  docs/rules/use-all.md
  fortitude_dev/src/generate_docs.rs
Labels: internal

#390 Add rule `double-precision-literal`
  docs/rules.md
  docs/rules/double-precision-literal.md
  fortitude/resources/test/fixtures/modernisation/MOD002.f90
  fortitude/src/rules/correctness/kind_suffixes.rs
  fortitude/src/rules/mod.rs
  fortitude/src/rules/modernisation/double_precision.rs
  fortitude/src/rules/modernisation/mod.rs
  fortitude/src/rules/modernisation/snapshots/fortitude__rules__modernisation__tests__double-precision-literal_MOD002.f90.snap
  fortitude/src/rules/modernisation/snapshots/fortitude__rules__modernisation__tests__double-precision_MOD001.f90.snap
Labels: rule

#386 Add rule to detect missing function result clause
  docs/rules.md
  docs/rules/function-missing-result.md
  fortitude/resources/test/fixtures/style/S221.f90
  fortitude/src/rules/mod.rs
  fortitude/src/rules/style/functions.rs
  fortitude/src/rules/style/mod.rs
  fortitude/src/rules/style/snapshots/fortitude__rules__style__tests__function-missing-result_S221.f90.snap
Labels: rule

#392 Fix some missing newlines at end of doc files
  docs/rules/double-precision-literal.md
  docs/rules/function-missing-result.md
Labels: internal
